# Set update schedule for Dependent Package Ecosystems

version: 2

updates:
  - package-ecosystem: docker
    directory: "/terraform/docker"
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: "/"
    schedule: { interval: weekly }
  - package-ecosystem: pip
    directory: "/terraform/docker"
    schedule: { interval: weekly }
    versioning-strategy: lockfile-only
  - package-ecosystem: bundler
    directory: "/terraform/docker"
    schedule: { interval: weekly }
